language: python
cache: pip
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6.3' # explicit branch used for deploying
branches:
  only:
    - master
    - /^v[0-9]/
before_install:
  - pip install virtualenv==20.0.1
  - pip install tox-travis
script:
  - tox
  - pip install -e .
before_deploy:
  - pip install -e .
  - make docs
deploy:
  - provider: pypi
    user: $PYPI_USERNAME
    api_key: $PYPI_PASSWORD
    skip-cleanup: true
    on:
      tags: true
      python: '3.6.3'
    distributions: "sdist bdist_wheel"
  - provider: pages
    local-dir: _docs
    github-token: $GITHUB_TOKEN
    skip-cleanup: true
    on:
      branch: master
      python: '3.6.3'
